minimum_reviewers: 2
docker: true
docker_image: "davidxd/yoko"
build_steps:
 - "env"
 - "echo $SHELL"
 - "make"
merge: true
org_mode: false
timeout: 2916
env:
 TEST_ENVIRONMENT: mytestvalue
 APP_VERSION: 23
 DIALYZER_PLT: .
